name: Vuepress CI Deploy

on: 
  push:
    branches: 
      - master

jobs:
  Vuepress-CI-Deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Use cached Node modules # 使用缓存
      uses: actions/cache@v1
      with:
        path: node_modules
        key: nodeModules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          nodeModules-
       
    - name: Generate
      run: |
        yarn install
        yarn build
    
    - name: Set timezone
      run: sudo timedatectl set-timezone "Asia/Shanghai"
      
    - name: Deploy
      env:
        GH_NAME: moreant
        GH_EMAIL: 552191481@qq.com
        GH_REF: github.com/moreant/notebook
        GH_TOKEN: ${{ secrets.TOKEN  }}
      run: |
        git config --global user.name $GH_NAME
        git config --global user.email $GH_EMAIL
        git clone https://"$GH_REF" deploy
        cd deploy
        git checkout gh-pages
        cd ../
        mv deploy/.git/ ./docs/.vuepress/dist/
        cd ./docs/.vuepress/dist/
        git add -A
        git commit -m "CI built at `date +"%Y-%m-%d %H:%M:%S"`"
        git push --force "https://"$GH_TOKEN"@"$GH_REF"" gh-pages:gh-pages